import { ReactNode } from 'react'

export const metadata = {
	title: 'Dashboard',
	description: 'Generated by Next.js',
}

export default function DashboardLayout({ children }: { children: ReactNode }) {
	return (
		<html lang="en">
			DASHBOARD HEADER
			<body>{children}</body>
		</html>
	)
}
